name: hola-mundo
run-name: ¡Estoy aprendiendo!
on:
  push: #push
  workflow_dispatch: #dispath
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node
      - name: Add enviroment
        run: echo "NAME=${{ github.actor }}" >> .env
      - name: Correr script
        run: node --env-file=.env holamundo.js