name: Trigers
run-name: Aprendiendo triggers
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      usuario:
        descriptions: 'Usuario de github'
        required: true
        type: string
  issue_comment:
    types: [created]
jobs:
  steps:
    hola-mundo:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Saludar
        run: echo "Hola ${{ inputs.usuario }}" 
    

